# Generated by Django 3.1.3 on 2021-01-28 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='编号')),
                ('type', models.CharField(max_length=20, verbose_name='类型')),
                ('describe', models.CharField(max_length=1024, verbose_name='描述')),
                ('opA', models.CharField(max_length=1024, verbose_name='选项A')),
                ('opB', models.CharField(max_length=1024, verbose_name='选项B')),
                ('opC', models.CharField(max_length=1024, verbose_name='选项C')),
                ('opD', models.CharField(max_length=1024, verbose_name='选项D')),
                ('answer', models.CharField(max_length=1024, verbose_name='答案')),
                ('difficulty', models.IntegerField(verbose_name='难度')),
            ],
            options={
                'db_table': 'problem',
            },
        ),
    ]
